import 'package:flutter/material.dart';
import '../screens/restaurants/restaurants_screen.dart' show RestaurantData;
import '../screens/hotels/hotels_screen.dart' show HotelData;
import '../screens/pharmacies/pharmacies_screen.dart' show PharmacyData;
import '../screens/attractions/attractions_screen.dart' show AttractionData;
import '../screens/shopping/shopping_screen.dart' show ShoppingVenueData;
import '../screens/category/category_data.dart' show ListingItem;
import '../screens/news/news_screen.dart' show NewsArticle;
import '../screens/events/events_data.dart' show EventItem;

// ==================== المطاعم ====================
Map<String, dynamic> restaurantToMap(RestaurantData r) => {
  'nameAr': r.nameAr,
  'nameEn': r.nameEn,
  'categoryAr': r.categoryAr,
  'categoryEn': r.categoryEn,
  'cuisineKey': r.cuisineKey,
  'locationAr': r.locationAr,
  'locationEn': r.locationEn,
  'rating': r.rating,
  'reviews': r.reviews,
  'priceRange': r.priceRange,
  'priceTier': r.priceTier,
  'time': r.time,
  'aboutAr': r.aboutAr,
  'aboutEn': r.aboutEn,
  'image': r.image,
  'iconCodePoint': r.placeholderIcon.codePoint,
  'colorValue': r.placeholderColor.toARGB32(),
  'customImageBase64': r.customImageBase64,
  'isFeatured': r.isFeatured,
  'phone': r.phone,
  'lat': r.lat,
  'lng': r.lng,
};

RestaurantData mapToRestaurant(Map<String, dynamic> m) => RestaurantData(
  nameAr: m['nameAr'] ?? '',
  nameEn: m['nameEn'] ?? '',
  categoryAr: m['categoryAr'] ?? '',
  categoryEn: m['categoryEn'] ?? '',
  cuisineKey: m['cuisineKey'] ?? 'traditional',
  locationAr: m['locationAr'] ?? '',
  locationEn: m['locationEn'] ?? '',
  rating: (m['rating'] as num?)?.toDouble() ?? 4.0,
  reviews: (m['reviews'] as num?)?.toInt() ?? 0,
  priceRange: m['priceRange'] ?? '',
  priceTier: m['priceTier'] ?? 'medium',
  time: m['time'] ?? '',
  aboutAr: m['aboutAr'] ?? '',
  aboutEn: m['aboutEn'] ?? '',
  image: m['image'] ?? 'assets/images/restaurants/custom.jpg',
  placeholderIcon: IconData(
    m['iconCodePoint'] ?? Icons.restaurant.codePoint,
    fontFamily: 'MaterialIcons',
  ),
  placeholderColor: Color(m['colorValue'] ?? 0xFF6C5CE7),
  customImageBase64: m['customImageBase64'],
  isFeatured: m['isFeatured'] ?? false,
  phone: m['phone'] ?? '',
  lat: (m['lat'] as num?)?.toDouble(),
  lng: (m['lng'] as num?)?.toDouble(),
);

// ==================== الفنادق ====================
Map<String, dynamic> hotelToMap(HotelData h) => {
  'nameAr': h.nameAr,
  'nameEn': h.nameEn,
  'typeAr': h.typeAr,
  'typeEn': h.typeEn,
  'locationAr': h.locationAr,
  'locationEn': h.locationEn,
  'rating': h.rating,
  'reviews': h.reviews,
  'priceInfoAr': h.priceInfoAr,
  'priceInfoEn': h.priceInfoEn,
  'priceTier': h.priceTier,
  'hoursAr': h.hoursAr,
  'hoursEn': h.hoursEn,
  'aboutAr': h.aboutAr,
  'aboutEn': h.aboutEn,
  'phone': h.phone,
  'image': h.image,
  'gallery': h.gallery,
  'amenities': h.amenities,
  'tags': h.tags,
  'iconCodePoint': h.placeholderIcon.codePoint,
  'colorValue': h.placeholderColor.toARGB32(),
  'customImageBase64': h.customImageBase64,
  'isFeatured': h.isFeatured,
  'lat': h.lat,
  'lng': h.lng,
};

HotelData mapToHotel(Map<String, dynamic> m) => HotelData(
  nameAr: m['nameAr'] ?? '',
  nameEn: m['nameEn'] ?? '',
  typeAr: m['typeAr'] ?? '',
  typeEn: m['typeEn'] ?? '',
  locationAr: m['locationAr'] ?? '',
  locationEn: m['locationEn'] ?? '',
  rating: (m['rating'] as num?)?.toDouble() ?? 4.0,
  reviews: (m['reviews'] as num?)?.toInt() ?? 0,
  // نقرأ infoLabelAr/En كاحتياط للبيانات القديمة المخزّنة قبل تحويل الفنادق
  // لنموذجها الخاص (كانت تشارك نموذج ListingItem العام).
  priceInfoAr: m['priceInfoAr'] ?? m['infoLabelAr'] ?? '',
  priceInfoEn: m['priceInfoEn'] ?? m['infoLabelEn'] ?? '',
  priceTier: m['priceTier'] ?? 'medium',
  hoursAr: m['hoursAr'] ?? '',
  hoursEn: m['hoursEn'] ?? '',
  aboutAr: m['aboutAr'] ?? '',
  aboutEn: m['aboutEn'] ?? '',
  phone: m['phone'] ?? '',
  image: m['image'] ?? '',
  gallery: (m['gallery'] as List?)?.cast<String>() ?? const [],
  amenities: (m['amenities'] as List?)?.cast<String>() ?? const [],
  tags: (m['tags'] as List?)?.cast<String>() ?? const [],
  placeholderIcon: IconData(
    m['iconCodePoint'] ?? Icons.hotel.codePoint,
    fontFamily: 'MaterialIcons',
  ),
  placeholderColor: Color(m['colorValue'] ?? 0xFF6C5CE7),
  customImageBase64: m['customImageBase64'],
  isFeatured: m['isFeatured'] ?? false,
  lat: (m['lat'] as num?)?.toDouble(),
  lng: (m['lng'] as num?)?.toDouble(),
);

// ==================== الصيدليات ====================
Map<String, dynamic> pharmacyToMap(PharmacyData p) => {
  'nameAr': p.nameAr,
  'nameEn': p.nameEn,
  'locationAr': p.locationAr,
  'locationEn': p.locationEn,
  'rating': p.rating,
  'reviews': p.reviews,
  'hoursAr': p.hoursAr,
  'hoursEn': p.hoursEn,
  'is24Hours': p.is24Hours,
  'hasDelivery': p.hasDelivery,
  'aboutAr': p.aboutAr,
  'aboutEn': p.aboutEn,
  'phone': p.phone,
  'image': p.image,
  'tags': p.tags,
  'iconCodePoint': p.placeholderIcon.codePoint,
  'colorValue': p.placeholderColor.toARGB32(),
  'customImageBase64': p.customImageBase64,
  'isFeatured': p.isFeatured,
  'lat': p.lat,
  'lng': p.lng,
};

PharmacyData mapToPharmacy(Map<String, dynamic> m) => PharmacyData(
  nameAr: m['nameAr'] ?? '',
  nameEn: m['nameEn'] ?? '',
  locationAr: m['locationAr'] ?? '',
  locationEn: m['locationEn'] ?? '',
  rating: (m['rating'] as num?)?.toDouble() ?? 4.0,
  reviews: (m['reviews'] as num?)?.toInt() ?? 0,
  hoursAr: m['hoursAr'] ?? '',
  hoursEn: m['hoursEn'] ?? '',
  is24Hours: m['is24Hours'] ?? false,
  hasDelivery: m['hasDelivery'] ?? false,
  aboutAr: m['aboutAr'] ?? '',
  aboutEn: m['aboutEn'] ?? '',
  phone: m['phone'] ?? '',
  image: m['image'] ?? '',
  tags: (m['tags'] as List?)?.cast<String>() ?? const [],
  placeholderIcon: IconData(
    m['iconCodePoint'] ?? Icons.local_pharmacy.codePoint,
    fontFamily: 'MaterialIcons',
  ),
  placeholderColor: Color(m['colorValue'] ?? 0xFF3B82F6),
  customImageBase64: m['customImageBase64'],
  isFeatured: m['isFeatured'] ?? false,
  lat: (m['lat'] as num?)?.toDouble(),
  lng: (m['lng'] as num?)?.toDouble(),
);

// ==================== المعالم السياحية ====================
Map<String, dynamic> attractionToMap(AttractionData a) => {
  'nameAr': a.nameAr,
  'nameEn': a.nameEn,
  'categories': a.categories,
  'locationAr': a.locationAr,
  'locationEn': a.locationEn,
  'rating': a.rating,
  'reviews': a.reviews,
  'aboutAr': a.aboutAr,
  'aboutEn': a.aboutEn,
  'visitHoursAr': a.visitHoursAr,
  'visitHoursEn': a.visitHoursEn,
  'entryFeeAr': a.entryFeeAr,
  'entryFeeEn': a.entryFeeEn,
  'image': a.image,
  'iconCodePoint': a.placeholderIcon.codePoint,
  'colorValue': a.placeholderColor.toARGB32(),
  'customImageBase64': a.customImageBase64,
  'isFeatured': a.isFeatured,
  'lat': a.lat,
  'lng': a.lng,
};

AttractionData mapToAttraction(Map<String, dynamic> m) => AttractionData(
  nameAr: m['nameAr'] ?? '',
  nameEn: m['nameEn'] ?? '',
  categories: (m['categories'] as List?)?.cast<String>() ?? const [],
  locationAr: m['locationAr'] ?? '',
  locationEn: m['locationEn'] ?? '',
  rating: (m['rating'] as num?)?.toDouble() ?? 4.0,
  reviews: (m['reviews'] as num?)?.toInt() ?? 0,
  aboutAr: m['aboutAr'] ?? '',
  aboutEn: m['aboutEn'] ?? '',
  visitHoursAr: m['visitHoursAr'] ?? '',
  visitHoursEn: m['visitHoursEn'] ?? '',
  entryFeeAr: m['entryFeeAr'] ?? '',
  entryFeeEn: m['entryFeeEn'] ?? '',
  image: m['image'] ?? '',
  placeholderIcon: IconData(
    m['iconCodePoint'] ?? Icons.account_balance.codePoint,
    fontFamily: 'MaterialIcons',
  ),
  placeholderColor: Color(m['colorValue'] ?? 0xFFC9A227),
  customImageBase64: m['customImageBase64'],
  isFeatured: m['isFeatured'] ?? false,
  lat: (m['lat'] as num?)?.toDouble(),
  lng: (m['lng'] as num?)?.toDouble(),
);

// ==================== المراكز التجارية (تسوق) ====================
Map<String, dynamic> shoppingVenueToMap(ShoppingVenueData v) => {
  'nameAr': v.nameAr,
  'nameEn': v.nameEn,
  'typeAr': v.typeAr,
  'typeEn': v.typeEn,
  'locationAr': v.locationAr,
  'locationEn': v.locationEn,
  'rating': v.rating,
  'reviews': v.reviews,
  'hoursAr': v.hoursAr,
  'hoursEn': v.hoursEn,
  'aboutAr': v.aboutAr,
  'aboutEn': v.aboutEn,
  'phone': v.phone,
  'image': v.image,
  'iconCodePoint': v.placeholderIcon.codePoint,
  'colorValue': v.placeholderColor.toARGB32(),
  'customImageBase64': v.customImageBase64,
  'isFeatured': v.isFeatured,
  'lat': v.lat,
  'lng': v.lng,
};

ShoppingVenueData mapToShoppingVenue(Map<String, dynamic> m) => ShoppingVenueData(
  nameAr: m['nameAr'] ?? '',
  nameEn: m['nameEn'] ?? '',
  typeAr: m['typeAr'] ?? '',
  typeEn: m['typeEn'] ?? '',
  locationAr: m['locationAr'] ?? '',
  locationEn: m['locationEn'] ?? '',
  rating: (m['rating'] as num?)?.toDouble() ?? 4.0,
  reviews: (m['reviews'] as num?)?.toInt() ?? 0,
  hoursAr: m['hoursAr'] ?? m['infoLabelAr'] ?? '',
  hoursEn: m['hoursEn'] ?? m['infoLabelEn'] ?? '',
  aboutAr: m['aboutAr'] ?? '',
  aboutEn: m['aboutEn'] ?? '',
  phone: m['phone'] ?? '',
  image: m['image'] ?? '',
  placeholderIcon: IconData(
    m['iconCodePoint'] ?? Icons.shopping_bag.codePoint,
    fontFamily: 'MaterialIcons',
  ),
  placeholderColor: Color(m['colorValue'] ?? 0xFF3B82F6),
  customImageBase64: m['customImageBase64'],
  isFeatured: m['isFeatured'] ?? false,
  lat: (m['lat'] as num?)?.toDouble(),
  lng: (m['lng'] as num?)?.toDouble(),
);

// ==================== العناصر العامة (سياحة/تسوق/مواصلات/صحة) ====================
Map<String, dynamic> listingToMap(ListingItem it) => {
  'nameAr': it.nameAr,
  'nameEn': it.nameEn,
  'typeAr': it.typeAr,
  'typeEn': it.typeEn,
  'locationAr': it.locationAr,
  'locationEn': it.locationEn,
  'rating': it.rating,
  'reviews': it.reviews,
  'infoLabelAr': it.infoLabelAr,
  'infoLabelEn': it.infoLabelEn,
  'aboutAr': it.aboutAr,
  'aboutEn': it.aboutEn,
  'phone': it.phone,
  'photoQuery': it.photoQuery,
  'iconCodePoint': it.placeholderIcon.codePoint,
  'colorValue': it.placeholderColor.toARGB32(),
  'customImageBase64': it.customImageBase64,
  'isFeatured': it.isFeatured,
  'image': it.image,
  'lat': it.lat,
  'lng': it.lng,
  'subTypeKey': it.subTypeKey,
};

ListingItem mapToListing(Map<String, dynamic> m) => ListingItem(
  nameAr: m['nameAr'] ?? '',
  nameEn: m['nameEn'] ?? '',
  typeAr: m['typeAr'] ?? '',
  typeEn: m['typeEn'] ?? '',
  locationAr: m['locationAr'] ?? '',
  locationEn: m['locationEn'] ?? '',
  rating: (m['rating'] as num?)?.toDouble() ?? 4.0,
  reviews: (m['reviews'] as num?)?.toInt() ?? 0,
  infoLabelAr: m['infoLabelAr'] ?? '',
  infoLabelEn: m['infoLabelEn'] ?? '',
  aboutAr: m['aboutAr'] ?? '',
  aboutEn: m['aboutEn'] ?? '',
  phone: m['phone'] ?? '+970 59 000 0000',
  photoQuery: m['photoQuery'] ?? 'nablus palestine city',
  placeholderIcon: IconData(
    m['iconCodePoint'] ?? Icons.place.codePoint,
    fontFamily: 'MaterialIcons',
  ),
  placeholderColor: Color(m['colorValue'] ?? 0xFF3B82F6),
  customImageBase64: m['customImageBase64'],
  isFeatured: m['isFeatured'] ?? false,
  image: m['image'],
  lat: (m['lat'] as num?)?.toDouble(),
  lng: (m['lng'] as num?)?.toDouble(),
  subTypeKey: m['subTypeKey'],
);

// ==================== الأخبار ====================
Map<String, dynamic> newsToMap(NewsArticle a) => {
  'titleAr': a.titleAr,
  'titleEn': a.titleEn,
  'dateAr': a.dateAr,
  'dateEn': a.dateEn,
  'categoryAr': a.categoryAr,
  'categoryEn': a.categoryEn,
  'categoryKey': a.categoryKey,
  'summaryAr': a.summaryAr,
  'summaryEn': a.summaryEn,
  'bodyAr': a.bodyAr,
  'bodyEn': a.bodyEn,
  'customImageBase64': a.customImageBase64,
};

NewsArticle mapToNews(Map<String, dynamic> m) => NewsArticle(
  titleAr: m['titleAr'] ?? '',
  titleEn: m['titleEn'] ?? '',
  dateAr: m['dateAr'] ?? '',
  dateEn: m['dateEn'] ?? '',
  categoryAr: m['categoryAr'] ?? '',
  categoryEn: m['categoryEn'] ?? '',
  categoryKey: m['categoryKey'] ?? 'events',
  summaryAr: m['summaryAr'] ?? '',
  summaryEn: m['summaryEn'] ?? '',
  bodyAr: m['bodyAr'] ?? '',
  bodyEn: m['bodyEn'] ?? '',
  customImageBase64: m['customImageBase64'],
);

// ==================== الفعاليات القادمة ====================
Map<String, dynamic> eventToMap(EventItem e) => {
  'titleAr': e.titleAr,
  'titleEn': e.titleEn,
  'venueAr': e.venueAr,
  'venueEn': e.venueEn,
  'day': e.day,
  'monthAr': e.monthAr,
  'monthEn': e.monthEn,
  'timeAr': e.timeAr,
  'timeEn': e.timeEn,
  'aboutAr': e.aboutAr,
  'aboutEn': e.aboutEn,
  'photoQuery': e.photoQuery,
  'iconCodePoint': e.icon.codePoint,
  'colorValue': e.color.toARGB32(),
  'customImageBase64': e.customImageBase64,
};

EventItem mapToEvent(Map<String, dynamic> m) => EventItem(
  titleAr: m['titleAr'] ?? '',
  titleEn: m['titleEn'] ?? '',
  venueAr: m['venueAr'] ?? '',
  venueEn: m['venueEn'] ?? '',
  day: m['day'] ?? '',
  monthAr: m['monthAr'] ?? '',
  monthEn: m['monthEn'] ?? '',
  timeAr: m['timeAr'] ?? '',
  timeEn: m['timeEn'] ?? '',
  aboutAr: m['aboutAr'] ?? '',
  aboutEn: m['aboutEn'] ?? '',
  photoQuery: m['photoQuery'] ?? 'nablus palestine city',
  icon: IconData(m['iconCodePoint'] ?? Icons.event.codePoint, fontFamily: 'MaterialIcons'),
  color: Color(m['colorValue'] ?? 0xFF3B82F6),
  customImageBase64: m['customImageBase64'],
);