import 'package:flutter/material.dart';

/// عنصر عام يمثل أي مكان بأي تصنيف (فندق، معلم سياحي، صيدلية...)
class ListingItem {
  final String nameAr;
  final String nameEn;
  final String typeAr; // وصف قصير مثل "فندق 4 نجوم" أو "صيدلية 24 ساعة"
  final String typeEn;
  final String locationAr;
  final String locationEn;
  final double rating;
  final int reviews;
  final String infoLabelAr; // تسمية السطر الإضافي: السعر / ساعات العمل / نوع الخدمة
  final String infoLabelEn;
  final String aboutAr;
  final String aboutEn;
  final String phone;
  final String photoQuery; // كلمة بحث إنجليزية لجلب صورة حقيقية مرتبطة بالموضوع
  final IconData placeholderIcon;
  final Color placeholderColor;
  final String? customImageBase64; // صورة رفعها الأدمن يدويًا لهذا العنصر تحديدًا
  final bool isFeatured; // مكان مميز/مروَّج له من الأدمن، يظهر أولًا وبشارة خاصة

  ListingItem({
    required this.nameAr,
    required this.nameEn,
    required this.typeAr,
    required this.typeEn,
    required this.locationAr,
    required this.locationEn,
    required this.rating,
    required this.reviews,
    required this.infoLabelAr,
    required this.infoLabelEn,
    required this.aboutAr,
    required this.aboutEn,
    this.phone = '+970 59 000 0000',
    required this.photoQuery,
    required this.placeholderIcon,
    required this.placeholderColor,
    this.customImageBase64,
    this.isFeatured = false,
  });
}

// ==================== الفنادق ====================
final List<ListingItem> hotelsData = [
  ListingItem(
    nameAr: 'فندق قصر نابلس',
    nameEn: 'Nablus Palace Hotel',
    typeAr: 'فندق 4 نجوم',
    typeEn: '4-Star Hotel',
    locationAr: 'شارع الجامعة - نابلس',
    locationEn: 'University St. - Nablus',
    rating: 4.5,
    reviews: 180,
    infoLabelAr: '180-250 ₪ / ليلة',
    infoLabelEn: '180-250 ₪ / night',
    aboutAr: 'فندق راقٍ بإطلالة على المدينة، يضم غرف مريحة ومطعم داخلي وخدمة استقبال على مدار الساعة.',
    aboutEn: 'An elegant hotel with a city view, comfortable rooms, an in-house restaurant, and 24-hour front desk service.',
    photoQuery: 'hotel exterior building',
    placeholderIcon: Icons.hotel,
    placeholderColor: Color(0xFF6C5CE7),
    isFeatured: true,
  ),
  ListingItem(
    nameAr: 'فندق نابلس الدولي',
    nameEn: 'Nablus International Hotel',
    typeAr: 'فندق 3 نجوم',
    typeEn: '3-Star Hotel',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.2,
    reviews: 120,
    infoLabelAr: '120-180 ₪ / ليلة',
    infoLabelEn: '120-180 ₪ / night',
    aboutAr: 'فندق اقتصادي بموقع مركزي قريب من الأسواق والمعالم السياحية الرئيسية.',
    aboutEn: 'A budget-friendly hotel in a central location near the main markets and tourist attractions.',
    photoQuery: 'hotel lobby',
    placeholderIcon: Icons.hotel,
    placeholderColor: Color(0xFF4C6EF5),
  ),
  ListingItem(
    nameAr: 'شقق الرابية المفروشة',
    nameEn: 'Al-Rabya Furnished Apartments',
    typeAr: 'شقق فندقية',
    typeEn: 'Serviced Apartments',
    locationAr: 'منطقة الرابية - نابلس',
    locationEn: 'Al-Rabya Area - Nablus',
    rating: 4.4,
    reviews: 95,
    infoLabelAr: '150-220 ₪ / ليلة',
    infoLabelEn: '150-220 ₪ / night',
    aboutAr: 'شقق مفروشة بالكامل مناسبة للإقامات الطويلة والعائلات، مع مطبخ خاص وموقف سيارات.',
    aboutEn: 'Fully furnished apartments suitable for long stays and families, with a private kitchen and parking.',
    photoQuery: 'furnished apartment interior',
    placeholderIcon: Icons.apartment,
    placeholderColor: Color(0xFF22C55E),
  ),
  ListingItem(
    nameAr: 'نزل البلدة القديمة',
    nameEn: 'Old City Guesthouse',
    typeAr: 'نزل تراثي',
    typeEn: 'Heritage Guesthouse',
    locationAr: 'البلدة القديمة - نابلس',
    locationEn: 'Old City - Nablus',
    rating: 4.7,
    reviews: 140,
    infoLabelAr: '100-160 ₪ / ليلة',
    infoLabelEn: '100-160 ₪ / night',
    aboutAr: 'إقامة فريدة داخل بيت تراثي مرمم بالبلدة القديمة، تجربة أصيلة وسط أزقة نابلس التاريخية.',
    aboutEn: 'A unique stay inside a restored heritage house in the Old City, an authentic experience among Nablus historic alleys.',
    photoQuery: 'traditional guesthouse interior',
    placeholderIcon: Icons.villa,
    placeholderColor: Color(0xFFC9A227),
  ),
];

// ==================== سياحة ومعالم ====================
final List<ListingItem> attractionsData = [
  ListingItem(
    nameAr: 'البلدة القديمة',
    nameEn: 'Old City',
    typeAr: 'معلم تاريخي',
    typeEn: 'Historic Landmark',
    locationAr: 'وسط نابلس',
    locationEn: 'Central Nablus',
    rating: 4.8,
    reviews: 520,
    infoLabelAr: 'دخول مجاني',
    infoLabelEn: 'Free entry',
    aboutAr: 'قلب نابلس التاريخي، أزقة ضيقة وأسواق تراثية وعمارة عثمانية ومملوكية عريقة.',
    aboutEn: 'The historic heart of Nablus, with narrow alleys, heritage markets, and ancient Ottoman and Mamluk architecture.',
    photoQuery: 'old town stone alley',
    placeholderIcon: Icons.account_balance,
    placeholderColor: Color(0xFFC9A227),
    isFeatured: true,
  ),
  ListingItem(
    nameAr: 'جبل جرزيم',
    nameEn: 'Mount Gerizim',
    typeAr: 'معلم طبيعي وديني',
    typeEn: 'Natural & Religious Landmark',
    locationAr: 'جنوب نابلس',
    locationEn: 'South Nablus',
    rating: 4.7,
    reviews: 310,
    infoLabelAr: 'دخول مجاني',
    infoLabelEn: 'Free entry',
    aboutAr: 'جبل مقدس عند السامريين، يوفر إطلالة بانورامية رائعة على مدينة نابلس بالكامل.',
    aboutEn: 'A mountain sacred to the Samaritans, offering a stunning panoramic view over the entire city of Nablus.',
    photoQuery: 'mountain landscape',
    placeholderIcon: Icons.terrain,
    placeholderColor: Color(0xFF4C8C4A),
  ),
  ListingItem(
    nameAr: 'خان الوكالة',
    nameEn: 'Khan Al-Wakala',
    typeAr: 'معلم تاريخي',
    typeEn: 'Historic Landmark',
    locationAr: 'البلدة القديمة - نابلس',
    locationEn: 'Old City - Nablus',
    rating: 4.6,
    reviews: 210,
    infoLabelAr: 'دخول مجاني',
    infoLabelEn: 'Free entry',
    aboutAr: 'خان تاريخي كان محطة رئيسية للقوافل التجارية، يعكس عراقة نابلس التجارية القديمة.',
    aboutEn: 'A historic caravanserai that was a major stop for trade caravans, reflecting the ancient commercial legacy of Nablus.',
    photoQuery: 'historic market caravanserai',
    placeholderIcon: Icons.location_city,
    placeholderColor: Color(0xFF9C6B30),
  ),
  ListingItem(
    nameAr: 'جامع الساطون',
    nameEn: 'Al-Satoun Mosque',
    typeAr: 'معلم ديني',
    typeEn: 'Religious Landmark',
    locationAr: 'البلدة القديمة - نابلس',
    locationEn: 'Old City - Nablus',
    rating: 4.7,
    reviews: 180,
    infoLabelAr: 'دخول مجاني',
    infoLabelEn: 'Free entry',
    aboutAr: 'أحد أقدم وأجمل المساجد التاريخية بنابلس، بعمارة إسلامية أصيلة.',
    aboutEn: 'One of the oldest and most beautiful historic mosques in Nablus, with authentic Islamic architecture.',
    photoQuery: 'mosque islamic architecture',
    placeholderIcon: Icons.mosque,
    placeholderColor: Color(0xFFB5651D),
  ),
  ListingItem(
    nameAr: 'حديقة التعاون',
    nameEn: 'Al-Taawon Park',
    typeAr: 'حديقة عامة',
    typeEn: 'Public Park',
    locationAr: 'شرق نابلس',
    locationEn: 'East Nablus',
    rating: 4.4,
    reviews: 260,
    infoLabelAr: 'دخول مجاني',
    infoLabelEn: 'Free entry',
    aboutAr: 'حديقة عامة واسعة مناسبة للعائلات، فيها مساحات خضراء وألعاب أطفال ومسارات مشي.',
    aboutEn: 'A large public park suitable for families, with green spaces, children\'s play areas, and walking trails.',
    photoQuery: 'public park garden',
    placeholderIcon: Icons.park,
    placeholderColor: Color(0xFF22C55E),
  ),
];

// ==================== التسوق ====================
final List<ListingItem> shoppingData = [
  ListingItem(
    nameAr: 'مركز نابلس مول',
    nameEn: 'Nablus Mall',
    typeAr: 'مركز تسوق',
    typeEn: 'Shopping Mall',
    locationAr: 'شارع رفيديا - نابلس',
    locationEn: 'Rafidia St. - Nablus',
    rating: 4.4,
    reviews: 340,
    infoLabelAr: 'يفتح 10ص - 10م',
    infoLabelEn: 'Open 10AM - 10PM',
    aboutAr: 'أكبر مركز تسوق بالمدينة يضم محلات أزياء عالمية ومحلية، مطاعم، وصالة ألعاب للأطفال.',
    aboutEn: 'The largest shopping mall in the city, featuring international and local fashion stores, restaurants, and a kids\' game arcade.',
    photoQuery: 'shopping mall interior',
    placeholderIcon: Icons.shopping_bag,
    placeholderColor: Color(0xFF3B82F6),
  ),
  ListingItem(
    nameAr: 'سوق البلدة القديمة',
    nameEn: 'Old City Market',
    typeAr: 'سوق تقليدي',
    typeEn: 'Traditional Market',
    locationAr: 'البلدة القديمة - نابلس',
    locationEn: 'Old City - Nablus',
    rating: 4.7,
    reviews: 410,
    infoLabelAr: 'يفتح 9ص - 8م',
    infoLabelEn: 'Open 9AM - 8PM',
    aboutAr: 'سوق شعبي عريق يبيع التوابل والحلويات النابلسية والمنتجات التقليدية اليدوية.',
    aboutEn: 'A historic traditional market selling spices, Nabulsi sweets, and traditional handmade products.',
    photoQuery: 'traditional market bazaar',
    placeholderIcon: Icons.storefront,
    placeholderColor: Color(0xFFB5651D),
  ),
  ListingItem(
    nameAr: 'مجمع رفيديا التجاري',
    nameEn: 'Rafidia Commercial Complex',
    typeAr: 'مجمع تجاري',
    typeEn: 'Commercial Complex',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 4.3,
    reviews: 190,
    infoLabelAr: 'يفتح 9ص - 9م',
    infoLabelEn: 'Open 9AM - 9PM',
    aboutAr: 'مجمع تجاري حديث يضم محلات إلكترونيات، ملابس، وأجهزة منزلية.',
    aboutEn: 'A modern commercial complex featuring electronics, clothing, and home appliance stores.',
    photoQuery: 'shopping center storefront',
    placeholderIcon: Icons.store,
    placeholderColor: Color(0xFFD4A017),
  ),
];

// ==================== المواصلات ====================
final List<ListingItem> transportData = [
  ListingItem(
    nameAr: 'محطة الباصات المركزية',
    nameEn: 'Central Bus Station',
    typeAr: 'محطة باصات',
    typeEn: 'Bus Station',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.1,
    reviews: 150,
    infoLabelAr: 'يعمل 6ص - 10م',
    infoLabelEn: 'Operates 6AM - 10PM',
    aboutAr: 'المحطة الرئيسية للباصات الرابطة بين نابلس والمدن المجاورة.',
    aboutEn: 'The main bus station connecting Nablus with neighboring cities.',
    photoQuery: 'bus station',
    placeholderIcon: Icons.directions_bus,
    placeholderColor: Color(0xFF14B8A6),
  ),
  ListingItem(
    nameAr: 'موقف سرفيس دوار الشهداء',
    nameEn: 'Martyrs Circle Service Taxi Stand',
    typeAr: 'سرفيس (تاكسي مشترك)',
    typeEn: 'Shared Taxi Stand',
    locationAr: 'دوار الشهداء - نابلس',
    locationEn: 'Martyrs Circle - Nablus',
    rating: 4.0,
    reviews: 90,
    infoLabelAr: 'يعمل طوال اليوم',
    infoLabelEn: 'Operates all day',
    aboutAr: 'موقف سيارات سرفيس يخدم معظم أحياء المدينة والمناطق المحيطة.',
    aboutEn: 'A shared taxi stand serving most neighborhoods of the city and surrounding areas.',
    photoQuery: 'taxi stand street',
    placeholderIcon: Icons.local_taxi,
    placeholderColor: Color(0xFFF5A623),
  ),
  ListingItem(
    nameAr: 'تأجير سيارات نابلس',
    nameEn: 'Nablus Car Rental',
    typeAr: 'تأجير سيارات',
    typeEn: 'Car Rental',
    locationAr: 'شارع الجامعة - نابلس',
    locationEn: 'University St. - Nablus',
    rating: 4.3,
    reviews: 75,
    infoLabelAr: 'يعمل 8ص - 8م',
    infoLabelEn: 'Open 8AM - 8PM',
    aboutAr: 'خدمة تأجير سيارات بأسعار مناسبة للزوار والسياح.',
    aboutEn: 'A car rental service with affordable prices for visitors and tourists.',
    photoQuery: 'car rental',
    placeholderIcon: Icons.car_rental,
    placeholderColor: Color(0xFF6C5CE7),
  ),
];

// ==================== الصحة ====================
final List<ListingItem> healthData = [
  ListingItem(
    nameAr: 'مستشفى النجاح الوطني الجامعي',
    nameEn: 'An-Najah National University Hospital',
    typeAr: 'مستشفى',
    typeEn: 'Hospital',
    locationAr: 'شارع رفيديا - نابلس',
    locationEn: 'Rafidia St. - Nablus',
    rating: 4.5,
    reviews: 420,
    infoLabelAr: 'طوارئ 24 ساعة',
    infoLabelEn: '24-hour emergency',
    aboutAr: 'مستشفى جامعي كبير يقدم خدمات طبية شاملة وطوارئ على مدار الساعة.',
    aboutEn: 'A large university hospital providing comprehensive medical services and round-the-clock emergency care.',
    photoQuery: 'hospital building',
    placeholderIcon: Icons.local_hospital,
    placeholderColor: Color(0xFFE85D5D),
  ),
  ListingItem(
    nameAr: 'مستشفى رفيديا الحكومي',
    nameEn: 'Rafidia Governmental Hospital',
    typeAr: 'مستشفى حكومي',
    typeEn: 'Governmental Hospital',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 4.2,
    reviews: 310,
    infoLabelAr: 'طوارئ 24 ساعة',
    infoLabelEn: '24-hour emergency',
    aboutAr: 'مستشفى حكومي رئيسي يخدم سكان المدينة والمناطق المحيطة.',
    aboutEn: 'A major governmental hospital serving the city\'s residents and surrounding areas.',
    photoQuery: 'hospital exterior',
    placeholderIcon: Icons.medical_services,
    placeholderColor: Color(0xFF3B82F6),
  ),
  ListingItem(
    nameAr: 'عيادة النور التخصصية',
    nameEn: 'Al-Noor Specialty Clinic',
    typeAr: 'عيادة تخصصية',
    typeEn: 'Specialty Clinic',
    locationAr: 'شارع فيصل - نابلس',
    locationEn: 'Faisal St. - Nablus',
    rating: 4.6,
    reviews: 130,
    infoLabelAr: 'يعمل 9ص - 6م',
    infoLabelEn: 'Open 9AM - 6PM',
    aboutAr: 'عيادة متخصصة بالكشف والاستشارات الطبية بأحدث الأجهزة.',
    aboutEn: 'A specialty clinic offering medical examinations and consultations with the latest equipment.',
    photoQuery: 'medical clinic interior',
    placeholderIcon: Icons.health_and_safety,
    placeholderColor: Color(0xFF22C55E),
  ),
];

// ==================== التعليم ====================
final List<ListingItem> educationData = [
  ListingItem(
    nameAr: 'جامعة النجاح الوطنية',
    nameEn: 'An-Najah National University',
    typeAr: 'جامعة',
    typeEn: 'University',
    locationAr: 'الرابية - نابلس',
    locationEn: 'Al-Rabya - Nablus',
    rating: 4.7,
    reviews: 610,
    infoLabelAr: 'الدوام 8ص - 4م',
    infoLabelEn: 'Hours 8AM - 4PM',
    aboutAr: 'أكبر جامعة فلسطينية، تضم كليات متعددة وحرمًا جامعيًا حديثًا في الرابية.',
    aboutEn: 'The largest Palestinian university, with multiple faculties and a modern campus in Al-Rabya.',
    photoQuery: 'university campus',
    placeholderIcon: Icons.school,
    placeholderColor: Color(0xFF6C5CE7),
  ),
  ListingItem(
    nameAr: 'جامعة النجاح القديمة',
    nameEn: 'An-Najah Old Campus',
    typeAr: 'حرم جامعي',
    typeEn: 'University Campus',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.5,
    reviews: 240,
    infoLabelAr: 'الدوام 8ص - 4م',
    infoLabelEn: 'Hours 8AM - 4PM',
    aboutAr: 'الحرم التاريخي للجامعة بموقع مركزي وسط المدينة.',
    aboutEn: 'The university\'s historic campus, centrally located in the city.',
    photoQuery: 'university building',
    placeholderIcon: Icons.school,
    placeholderColor: Color(0xFF4C6EF5),
  ),
  ListingItem(
    nameAr: 'مدارس نابلس الثانوية',
    nameEn: 'Nablus Secondary Schools',
    typeAr: 'مدرسة',
    typeEn: 'School',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 4.2,
    reviews: 95,
    infoLabelAr: 'الدوام 7:30ص - 1:30م',
    infoLabelEn: 'Hours 7:30AM - 1:30PM',
    aboutAr: 'مجمع مدارس حكومية وخاصة يخدم أحياء المدينة المختلفة.',
    aboutEn: 'A cluster of public and private schools serving the city\'s different neighborhoods.',
    photoQuery: 'school building',
    placeholderIcon: Icons.menu_book,
    placeholderColor: Color(0xFF22C55E),
  ),
];

// ==================== البنوك والصرافة ====================
final List<ListingItem> banksData = [
  ListingItem(
    nameAr: 'بنك فلسطين - الفرع الرئيسي',
    nameEn: 'Bank of Palestine - Main Branch',
    typeAr: 'بنك',
    typeEn: 'Bank',
    locationAr: 'شارع الجامعة - نابلس',
    locationEn: 'University St. - Nablus',
    rating: 4.3,
    reviews: 210,
    infoLabelAr: 'يفتح 8:30ص - 3م',
    infoLabelEn: 'Open 8:30AM - 3PM',
    aboutAr: 'الفرع الرئيسي لأكبر بنك فلسطيني، يقدم كافة الخدمات المصرفية وصرافة العملات.',
    aboutEn: 'The main branch of the largest Palestinian bank, offering full banking and currency exchange services.',
    photoQuery: 'bank building',
    placeholderIcon: Icons.account_balance,
    placeholderColor: Color(0xFF14B8A6),
  ),
  ListingItem(
    nameAr: 'البنك العربي',
    nameEn: 'Arab Bank',
    typeAr: 'بنك',
    typeEn: 'Bank',
    locationAr: 'دوار الشهداء - نابلس',
    locationEn: 'Martyrs Circle - Nablus',
    rating: 4.1,
    reviews: 140,
    infoLabelAr: 'يفتح 8:30ص - 3م',
    infoLabelEn: 'Open 8:30AM - 3PM',
    aboutAr: 'فرع بنكي يقدم حسابات جارية وتوفير وخدمات تحويل الأموال.',
    aboutEn: 'A bank branch offering current and savings accounts and money transfer services.',
    photoQuery: 'bank exterior',
    placeholderIcon: Icons.account_balance,
    placeholderColor: Color(0xFF3B82F6),
  ),
  ListingItem(
    nameAr: 'صرافة الاتحاد',
    nameEn: 'Al-Ittihad Exchange',
    typeAr: 'محل صرافة',
    typeEn: 'Currency Exchange',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.4,
    reviews: 88,
    infoLabelAr: 'يفتح 9ص - 7م',
    infoLabelEn: 'Open 9AM - 7PM',
    aboutAr: 'محل صرافة موثوق لتبديل العملات الأجنبية بأسعار يومية محدثة.',
    aboutEn: 'A trusted currency exchange shop with daily updated rates.',
    photoQuery: 'currency exchange shop',
    placeholderIcon: Icons.currency_exchange,
    placeholderColor: Color(0xFFC9A227),
  ),
];

// ==================== الترفيه ====================
final List<ListingItem> entertainmentData = [
  ListingItem(
    nameAr: 'مدينة الملاهي نابلس',
    nameEn: 'Nablus Amusement Park',
    typeAr: 'مدينة ملاهي',
    typeEn: 'Amusement Park',
    locationAr: 'شرق نابلس',
    locationEn: 'East Nablus',
    rating: 4.3,
    reviews: 175,
    infoLabelAr: 'يفتح 3م - 11م',
    infoLabelEn: 'Open 3PM - 11PM',
    aboutAr: 'ألعاب متنوعة للأطفال والعائلات مع مساحات جلوس ومطاعم خفيفة.',
    aboutEn: 'A variety of rides for children and families, with seating areas and light dining.',
    photoQuery: 'amusement park rides',
    placeholderIcon: Icons.attractions,
    placeholderColor: Color(0xFFE85D5D),
  ),
  ListingItem(
    nameAr: 'سينما نابلس',
    nameEn: 'Nablus Cinema',
    typeAr: 'سينما',
    typeEn: 'Cinema',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 4.5,
    reviews: 230,
    infoLabelAr: 'يفتح 12م - 12ص',
    infoLabelEn: 'Open 12PM - 12AM',
    aboutAr: 'صالة عرض سينمائي بتقنية صوت وصورة حديثة وأحدث الأفلام.',
    aboutEn: 'A modern cinema hall with up-to-date sound and picture technology, showing the latest films.',
    photoQuery: 'cinema movie theater',
    placeholderIcon: Icons.local_movies,
    placeholderColor: Color(0xFF6C5CE7),
  ),
  ListingItem(
    nameAr: 'صالة بولينج نابلس',
    nameEn: 'Nablus Bowling Hall',
    typeAr: 'صالة ألعاب',
    typeEn: 'Bowling & Games Hall',
    locationAr: 'شارع الجامعة - نابلس',
    locationEn: 'University St. - Nablus',
    rating: 4.2,
    reviews: 98,
    infoLabelAr: 'يفتح 2م - 12ص',
    infoLabelEn: 'Open 2PM - 12AM',
    aboutAr: 'مسارات بولينج وألعاب فيديو مناسبة للشباب والعائلات.',
    aboutEn: 'Bowling lanes and video games suitable for youth and families.',
    photoQuery: 'bowling alley',
    placeholderIcon: Icons.sports_esports,
    placeholderColor: Color(0xFF22C55E),
  ),
];

// ==================== خدمات حكومية ====================
final List<ListingItem> governmentData = [
  ListingItem(
    nameAr: 'بلدية نابلس',
    nameEn: 'Nablus Municipality',
    typeAr: 'دائرة حكومية',
    typeEn: 'Government Office',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.0,
    reviews: 160,
    infoLabelAr: 'الدوام 8ص - 3م',
    infoLabelEn: 'Hours 8AM - 3PM',
    aboutAr: 'المقر الرئيسي لبلدية نابلس، يقدم خدمات الترخيص والمعاملات البلدية.',
    aboutEn: 'The main office of Nablus Municipality, providing licensing and municipal services.',
    photoQuery: 'municipality government building',
    placeholderIcon: Icons.account_balance,
    placeholderColor: Color(0xFF3B82F6),
  ),
  ListingItem(
    nameAr: 'دائرة الأحوال المدنية',
    nameEn: 'Civil Affairs Department',
    typeAr: 'دائرة حكومية',
    typeEn: 'Government Office',
    locationAr: 'شارع فيصل - نابلس',
    locationEn: 'Faisal St. - Nablus',
    rating: 3.9,
    reviews: 120,
    infoLabelAr: 'الدوام 8ص - 2:30م',
    infoLabelEn: 'Hours 8AM - 2:30PM',
    aboutAr: 'إصدار وتجديد الهويات ووثائق الأحوال المدنية.',
    aboutEn: 'Issuing and renewing IDs and civil status documents.',
    photoQuery: 'government office',
    placeholderIcon: Icons.badge,
    placeholderColor: Color(0xFF9C6B30),
  ),
  ListingItem(
    nameAr: 'مكتب البريد المركزي',
    nameEn: 'Central Post Office',
    typeAr: 'بريد',
    typeEn: 'Post Office',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.0,
    reviews: 70,
    infoLabelAr: 'الدوام 8ص - 3م',
    infoLabelEn: 'Hours 8AM - 3PM',
    aboutAr: 'خدمات البريد والطرود والتحويلات المالية.',
    aboutEn: 'Postal, parcel, and money transfer services.',
    photoQuery: 'post office',
    placeholderIcon: Icons.local_post_office,
    placeholderColor: Color(0xFFC9A227),
  ),
];

// ==================== الصيدليات ====================
final List<ListingItem> pharmaciesData = [
  ListingItem(
    nameAr: 'صيدلية النجاح',
    nameEn: 'Al-Najah Pharmacy',
    typeAr: 'صيدلية 24 ساعة',
    typeEn: '24-Hour Pharmacy',
    locationAr: 'شارع الجامعة - نابلس',
    locationEn: 'University St. - Nablus',
    rating: 4.5,
    reviews: 160,
    infoLabelAr: 'تعمل 24 ساعة',
    infoLabelEn: 'Open 24 hours',
    aboutAr: 'صيدلية تعمل على مدار الساعة، توفر جميع الأدوية والمستلزمات الطبية.',
    aboutEn: 'A pharmacy open around the clock, providing all medications and medical supplies.',
    photoQuery: 'pharmacy interior',
    placeholderIcon: Icons.local_pharmacy,
    placeholderColor: Color(0xFF3B82F6),
  ),
  ListingItem(
    nameAr: 'صيدلية الشفاء',
    nameEn: 'Al-Shifa Pharmacy',
    typeAr: 'صيدلية',
    typeEn: 'Pharmacy',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.3,
    reviews: 110,
    infoLabelAr: 'تعمل 8ص - 11م',
    infoLabelEn: 'Open 8AM - 11PM',
    aboutAr: 'صيدلية بموقع مركزي تقدم استشارات دوائية مجانية.',
    aboutEn: 'A centrally located pharmacy offering free medication consultations.',
    photoQuery: 'pharmacy shelves medicine',
    placeholderIcon: Icons.local_pharmacy,
    placeholderColor: Color(0xFF22C55E),
  ),
  ListingItem(
    nameAr: 'صيدلية الرحمة',
    nameEn: 'Al-Rahma Pharmacy',
    typeAr: 'صيدلية 24 ساعة',
    typeEn: '24-Hour Pharmacy',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 4.4,
    reviews: 140,
    infoLabelAr: 'تعمل 24 ساعة',
    infoLabelEn: 'Open 24 hours',
    aboutAr: 'صيدلية تعمل على مدار الساعة مع خدمة توصيل للمنازل.',
    aboutEn: 'A 24-hour pharmacy offering home delivery service.',
    photoQuery: 'pharmacy store',
    placeholderIcon: Icons.local_pharmacy,
    placeholderColor: Color(0xFFE85D5D),
  ),
  ListingItem(
    nameAr: 'صيدلية الأمل',
    nameEn: 'Al-Amal Pharmacy',
    typeAr: 'صيدلية',
    typeEn: 'Pharmacy',
    locationAr: 'شارع فيصل - نابلس',
    locationEn: 'Faisal St. - Nablus',
    rating: 4.2,
    reviews: 85,
    infoLabelAr: 'تعمل 8ص - 10م',
    infoLabelEn: 'Open 8AM - 10PM',
    aboutAr: 'صيدلية عائلية تقدم خدمة شخصية ومتابعة دقيقة للزبائن.',
    aboutEn: 'A family pharmacy offering personalized service and careful follow-up for customers.',
    photoQuery: 'pharmacy counter',
    placeholderIcon: Icons.local_pharmacy,
    placeholderColor: Color(0xFFC9A227),
  ),
];