import 'package:flutter/material.dart';

/// عنصر عام يمثل أي مكان بأي تصنيف (فندق، معلم سياحي، صيدلية...)
class ListingItem {
  final String nameAr;
  final String nameEn;
  final String typeAr; // وصف قصير مثل "فندق 4 نجوم" أو "صيدلية 24 ساعة"
  final String typeEn;
  final String locationAr;
  final String locationEn;
  final double rating;
  final int reviews;
  final String infoLabelAr; // تسمية السطر الإضافي: السعر / ساعات العمل / نوع الخدمة
  final String infoLabelEn;
  final String aboutAr;
  final String aboutEn;
  final String phone;
  final String photoQuery; // كلمة بحث إنجليزية لجلب صورة حقيقية مرتبطة بالموضوع
  final IconData placeholderIcon;
  final Color placeholderColor;
  final String? customImageBase64; // صورة رفعها الأدمن يدويًا لهذا العنصر تحديدًا
  final bool isFeatured; // مكان مميز/مروَّج له من الأدمن، يظهر أولًا وبشارة خاصة
  final String? image; // صورة حقيقية جاهزة بالمشروع (assets/...) لمكان حقيقي موثّق
  final double? lat; // إحداثيات دقيقة حقيقية (لو موجودة) بدل التقريب حسب الحي
  final double? lng;
  final String? subTypeKey; // مفتاح التصنيف الفرعي (مثلاً taxiOffices/busStations) لشاشات الاختيار الفرعي
  final String? serverImageUrl; // صورة رفعها الأدمن ومخزّنة على السيرفر (/uploads/...)

  ListingItem({
    required this.nameAr,
    required this.nameEn,
    required this.typeAr,
    required this.typeEn,
    required this.locationAr,
    required this.locationEn,
    required this.rating,
    required this.reviews,
    required this.infoLabelAr,
    required this.infoLabelEn,
    required this.aboutAr,
    required this.aboutEn,
    this.phone = '+970 59 000 0000',
    required this.photoQuery,
    required this.placeholderIcon,
    required this.placeholderColor,
    this.customImageBase64,
    this.isFeatured = false,
    this.image,
    this.lat,
    this.lng,
    this.subTypeKey,
    this.serverImageUrl,
  });
}

// ==================== الفنادق ====================
final List<ListingItem> hotelsData = [
  ListingItem(
    nameAr: 'فندق قصر نابلس',
    nameEn: 'Nablus Palace Hotel',
    typeAr: 'فندق 4 نجوم',
    typeEn: '4-Star Hotel',
    locationAr: 'شارع الجامعة - نابلس',
    locationEn: 'University St. - Nablus',
    rating: 4.5,
    reviews: 180,
    infoLabelAr: '180-250 ₪ / ليلة',
    infoLabelEn: '180-250 ₪ / night',
    aboutAr: 'فندق راقٍ بإطلالة على المدينة، يضم غرف مريحة ومطعم داخلي وخدمة استقبال على مدار الساعة.',
    aboutEn: 'An elegant hotel with a city view, comfortable rooms, an in-house restaurant, and 24-hour front desk service.',
    photoQuery: 'hotel exterior building',
    placeholderIcon: Icons.hotel,
    placeholderColor: Color(0xFF6C5CE7),
    isFeatured: true,
  ),
  ListingItem(
    nameAr: 'فندق نابلس الدولي',
    nameEn: 'Nablus International Hotel',
    typeAr: 'فندق 3 نجوم',
    typeEn: '3-Star Hotel',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.2,
    reviews: 120,
    infoLabelAr: '120-180 ₪ / ليلة',
    infoLabelEn: '120-180 ₪ / night',
    aboutAr: 'فندق اقتصادي بموقع مركزي قريب من الأسواق والمعالم السياحية الرئيسية.',
    aboutEn: 'A budget-friendly hotel in a central location near the main markets and tourist attractions.',
    photoQuery: 'hotel lobby',
    placeholderIcon: Icons.hotel,
    placeholderColor: Color(0xFF4C6EF5),
  ),
  ListingItem(
    nameAr: 'شقق الرابية المفروشة',
    nameEn: 'Al-Rabya Furnished Apartments',
    typeAr: 'شقق فندقية',
    typeEn: 'Serviced Apartments',
    locationAr: 'منطقة الرابية - نابلس',
    locationEn: 'Al-Rabya Area - Nablus',
    rating: 4.4,
    reviews: 95,
    infoLabelAr: '150-220 ₪ / ليلة',
    infoLabelEn: '150-220 ₪ / night',
    aboutAr: 'شقق مفروشة بالكامل مناسبة للإقامات الطويلة والعائلات، مع مطبخ خاص وموقف سيارات.',
    aboutEn: 'Fully furnished apartments suitable for long stays and families, with a private kitchen and parking.',
    photoQuery: 'furnished apartment interior',
    placeholderIcon: Icons.apartment,
    placeholderColor: Color(0xFF22C55E),
  ),
  ListingItem(
    nameAr: 'نزل البلدة القديمة',
    nameEn: 'Old City Guesthouse',
    typeAr: 'نزل تراثي',
    typeEn: 'Heritage Guesthouse',
    locationAr: 'البلدة القديمة - نابلس',
    locationEn: 'Old City - Nablus',
    rating: 4.7,
    reviews: 140,
    infoLabelAr: '100-160 ₪ / ليلة',
    infoLabelEn: '100-160 ₪ / night',
    aboutAr: 'إقامة فريدة داخل بيت تراثي مرمم بالبلدة القديمة، تجربة أصيلة وسط أزقة نابلس التاريخية.',
    aboutEn: 'A unique stay inside a restored heritage house in the Old City, an authentic experience among Nablus historic alleys.',
    photoQuery: 'traditional guesthouse interior',
    placeholderIcon: Icons.villa,
    placeholderColor: Color(0xFFC9A227),
  ),
];

// ==================== سياحة ومعالم ====================
final List<ListingItem> attractionsData = [
  ListingItem(
    nameAr: 'البلدة القديمة',
    nameEn: 'Old City',
    typeAr: 'معلم تاريخي',
    typeEn: 'Historic Landmark',
    locationAr: 'وسط نابلس',
    locationEn: 'Central Nablus',
    rating: 4.8,
    reviews: 520,
    infoLabelAr: 'دخول مجاني',
    infoLabelEn: 'Free entry',
    aboutAr: 'قلب نابلس التاريخي، أزقة ضيقة وأسواق تراثية وعمارة عثمانية ومملوكية عريقة.',
    aboutEn: 'The historic heart of Nablus, with narrow alleys, heritage markets, and ancient Ottoman and Mamluk architecture.',
    photoQuery: 'old town stone alley',
    placeholderIcon: Icons.account_balance,
    placeholderColor: Color(0xFFC9A227),
    isFeatured: true,
  ),
  ListingItem(
    nameAr: 'جبل جرزيم',
    nameEn: 'Mount Gerizim',
    typeAr: 'معلم طبيعي وديني',
    typeEn: 'Natural & Religious Landmark',
    locationAr: 'جنوب نابلس',
    locationEn: 'South Nablus',
    rating: 4.7,
    reviews: 310,
    infoLabelAr: 'دخول مجاني',
    infoLabelEn: 'Free entry',
    aboutAr: 'جبل مقدس عند السامريين، يوفر إطلالة بانورامية رائعة على مدينة نابلس بالكامل.',
    aboutEn: 'A mountain sacred to the Samaritans, offering a stunning panoramic view over the entire city of Nablus.',
    photoQuery: 'mountain landscape',
    placeholderIcon: Icons.terrain,
    placeholderColor: Color(0xFF4C8C4A),
  ),
  ListingItem(
    nameAr: 'خان الوكالة',
    nameEn: 'Khan Al-Wakala',
    typeAr: 'معلم تاريخي',
    typeEn: 'Historic Landmark',
    locationAr: 'البلدة القديمة - نابلس',
    locationEn: 'Old City - Nablus',
    rating: 4.6,
    reviews: 210,
    infoLabelAr: 'دخول مجاني',
    infoLabelEn: 'Free entry',
    aboutAr: 'خان تاريخي كان محطة رئيسية للقوافل التجارية، يعكس عراقة نابلس التجارية القديمة.',
    aboutEn: 'A historic caravanserai that was a major stop for trade caravans, reflecting the ancient commercial legacy of Nablus.',
    photoQuery: 'historic market caravanserai',
    placeholderIcon: Icons.location_city,
    placeholderColor: Color(0xFF9C6B30),
  ),
  ListingItem(
    nameAr: 'جامع الساطون',
    nameEn: 'Al-Satoun Mosque',
    typeAr: 'معلم ديني',
    typeEn: 'Religious Landmark',
    locationAr: 'البلدة القديمة - نابلس',
    locationEn: 'Old City - Nablus',
    rating: 4.7,
    reviews: 180,
    infoLabelAr: 'دخول مجاني',
    infoLabelEn: 'Free entry',
    aboutAr: 'أحد أقدم وأجمل المساجد التاريخية بنابلس، بعمارة إسلامية أصيلة.',
    aboutEn: 'One of the oldest and most beautiful historic mosques in Nablus, with authentic Islamic architecture.',
    photoQuery: 'mosque islamic architecture',
    placeholderIcon: Icons.mosque,
    placeholderColor: Color(0xFFB5651D),
  ),
  ListingItem(
    nameAr: 'حديقة التعاون',
    nameEn: 'Al-Taawon Park',
    typeAr: 'حديقة عامة',
    typeEn: 'Public Park',
    locationAr: 'شرق نابلس',
    locationEn: 'East Nablus',
    rating: 4.4,
    reviews: 260,
    infoLabelAr: 'دخول مجاني',
    infoLabelEn: 'Free entry',
    aboutAr: 'حديقة عامة واسعة مناسبة للعائلات، فيها مساحات خضراء وألعاب أطفال ومسارات مشي.',
    aboutEn: 'A large public park suitable for families, with green spaces, children\'s play areas, and walking trails.',
    photoQuery: 'public park garden',
    placeholderIcon: Icons.park,
    placeholderColor: Color(0xFF22C55E),
  ),
];

// ==================== التسوق ====================
final List<ListingItem> shoppingData = [
  ListingItem(
    nameAr: 'مركز نابلس مول',
    nameEn: 'Nablus Mall',
    typeAr: 'مركز تسوق',
    typeEn: 'Shopping Mall',
    locationAr: 'شارع رفيديا - نابلس',
    locationEn: 'Rafidia St. - Nablus',
    rating: 4.4,
    reviews: 340,
    infoLabelAr: 'يفتح 10ص - 10م',
    infoLabelEn: 'Open 10AM - 10PM',
    aboutAr: 'أكبر مركز تسوق بالمدينة يضم محلات أزياء عالمية ومحلية، مطاعم، وصالة ألعاب للأطفال.',
    aboutEn: 'The largest shopping mall in the city, featuring international and local fashion stores, restaurants, and a kids\' game arcade.',
    photoQuery: 'shopping mall interior',
    placeholderIcon: Icons.shopping_bag,
    placeholderColor: Color(0xFF3B82F6),
  ),
  ListingItem(
    nameAr: 'سوق البلدة القديمة',
    nameEn: 'Old City Market',
    typeAr: 'سوق تقليدي',
    typeEn: 'Traditional Market',
    locationAr: 'البلدة القديمة - نابلس',
    locationEn: 'Old City - Nablus',
    rating: 4.7,
    reviews: 410,
    infoLabelAr: 'يفتح 9ص - 8م',
    infoLabelEn: 'Open 9AM - 8PM',
    aboutAr: 'سوق شعبي عريق يبيع التوابل والحلويات النابلسية والمنتجات التقليدية اليدوية.',
    aboutEn: 'A historic traditional market selling spices, Nabulsi sweets, and traditional handmade products.',
    photoQuery: 'traditional market bazaar',
    placeholderIcon: Icons.storefront,
    placeholderColor: Color(0xFFB5651D),
  ),
  ListingItem(
    nameAr: 'مجمع رفيديا التجاري',
    nameEn: 'Rafidia Commercial Complex',
    typeAr: 'مجمع تجاري',
    typeEn: 'Commercial Complex',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 4.3,
    reviews: 190,
    infoLabelAr: 'يفتح 9ص - 9م',
    infoLabelEn: 'Open 9AM - 9PM',
    aboutAr: 'مجمع تجاري حديث يضم محلات إلكترونيات، ملابس، وأجهزة منزلية.',
    aboutEn: 'A modern commercial complex featuring electronics, clothing, and home appliance stores.',
    photoQuery: 'shopping center storefront',
    placeholderIcon: Icons.store,
    placeholderColor: Color(0xFFD4A017),
  ),
];

// ==================== المواصلات ====================
final List<ListingItem> transportData = [
  ListingItem(
    nameAr: 'محطة الباصات المركزية',
    nameEn: 'Central Bus Station',
    typeAr: 'محطة باصات',
    typeEn: 'Bus Station',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.1,
    reviews: 150,
    infoLabelAr: 'يعمل 6ص - 10م',
    infoLabelEn: 'Operates 6AM - 10PM',
    aboutAr: 'المحطة الرئيسية للباصات الرابطة بين نابلس والمدن المجاورة.',
    aboutEn: 'The main bus station connecting Nablus with neighboring cities.',
    photoQuery: 'bus station',
    placeholderIcon: Icons.directions_bus,
    placeholderColor: Color(0xFF14B8A6),
  ),
  ListingItem(
    nameAr: 'موقف سرفيس دوار الشهداء',
    nameEn: 'Martyrs Circle Service Taxi Stand',
    typeAr: 'سرفيس (تاكسي مشترك)',
    typeEn: 'Shared Taxi Stand',
    locationAr: 'دوار الشهداء - نابلس',
    locationEn: 'Martyrs Circle - Nablus',
    rating: 4.0,
    reviews: 90,
    infoLabelAr: 'يعمل طوال اليوم',
    infoLabelEn: 'Operates all day',
    aboutAr: 'موقف سيارات سرفيس يخدم معظم أحياء المدينة والمناطق المحيطة.',
    aboutEn: 'A shared taxi stand serving most neighborhoods of the city and surrounding areas.',
    photoQuery: 'taxi stand street',
    placeholderIcon: Icons.local_taxi,
    placeholderColor: Color(0xFFF5A623),
  ),
  ListingItem(
    nameAr: 'تأجير سيارات نابلس',
    nameEn: 'Nablus Car Rental',
    typeAr: 'تأجير سيارات',
    typeEn: 'Car Rental',
    locationAr: 'شارع الجامعة - نابلس',
    locationEn: 'University St. - Nablus',
    rating: 4.3,
    reviews: 75,
    infoLabelAr: 'يعمل 8ص - 8م',
    infoLabelEn: 'Open 8AM - 8PM',
    aboutAr: 'خدمة تأجير سيارات بأسعار مناسبة للزوار والسياح.',
    aboutEn: 'A car rental service with affordable prices for visitors and tourists.',
    photoQuery: 'car rental',
    placeholderIcon: Icons.car_rental,
    placeholderColor: Color(0xFF6C5CE7),
  ),
  ListingItem(
    nameAr: 'موقف سرفيس رفيديا',
    nameEn: 'Rafidia Service Taxi Stand',
    typeAr: 'سرفيس (تاكسي مشترك)',
    typeEn: 'Shared Taxi Stand',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 3.9,
    reviews: 62,
    infoLabelAr: 'يعمل 6ص - 9م',
    infoLabelEn: 'Operates 6AM - 9PM',
    aboutAr: 'موقف سرفيس يخدم منطقة رفيديا والقرى المجاورة.',
    aboutEn: 'A shared taxi stand serving the Rafidia area and nearby villages.',
    photoQuery: 'taxi stand street',
    placeholderIcon: Icons.local_taxi,
    placeholderColor: Color(0xFFF5A623),
  ),
  ListingItem(
    nameAr: 'محطة وقود البترول الوطنية',
    nameEn: 'National Petroleum Gas Station',
    typeAr: 'محطة وقود',
    typeEn: 'Gas Station',
    locationAr: 'شارع القدس - نابلس',
    locationEn: 'Al-Quds St. - Nablus',
    rating: 4.2,
    reviews: 110,
    infoLabelAr: 'يعمل 24 ساعة',
    infoLabelEn: 'Open 24 hours',
    aboutAr: 'محطة وقود ومتجر صغير، مفتوحة على مدار الساعة.',
    aboutEn: 'A gas station with a small convenience store, open around the clock.',
    photoQuery: 'gas station',
    placeholderIcon: Icons.local_gas_station,
    placeholderColor: Color(0xFFEF4444),
  ),
  ListingItem(
    nameAr: 'كراج صيانة السيارات الحديث',
    nameEn: 'Modern Auto Repair Garage',
    typeAr: 'صيانة سيارات',
    typeEn: 'Car Repair',
    locationAr: 'المنطقة الصناعية - نابلس',
    locationEn: 'Industrial Zone - Nablus',
    rating: 4.0,
    reviews: 54,
    infoLabelAr: 'يعمل 8ص - 6م',
    infoLabelEn: 'Open 8AM - 6PM',
    aboutAr: 'خدمات صيانة وإصلاح سيارات بخبرة طويلة.',
    aboutEn: 'Car maintenance and repair services with years of experience.',
    photoQuery: 'car repair garage',
    placeholderIcon: Icons.car_repair,
    placeholderColor: Color(0xFF6B7280),
  ),
  ListingItem(
    nameAr: 'موقف السيارات العام - وسط البلد',
    nameEn: 'Public Parking - City Center',
    typeAr: 'موقف سيارات',
    typeEn: 'Parking Lot',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 3.8,
    reviews: 45,
    infoLabelAr: 'يعمل 24 ساعة',
    infoLabelEn: 'Open 24 hours',
    aboutAr: 'موقف سيارات عام قريب من الأسواق والمناطق التجارية.',
    aboutEn: 'A public parking lot close to the markets and commercial areas.',
    photoQuery: 'parking lot',
    placeholderIcon: Icons.local_parking,
    placeholderColor: Color(0xFF3B82F6),
  ),
  ListingItem(
    nameAr: 'باصات نابلس - رام الله',
    nameEn: 'Nablus - Ramallah Bus Line',
    typeAr: 'خط باصات بين المدن',
    typeEn: 'Intercity Bus Line',
    locationAr: 'المحطة المركزية - نابلس',
    locationEn: 'Central Station - Nablus',
    rating: 4.1,
    reviews: 128,
    infoLabelAr: 'رحلات كل 30 دقيقة',
    infoLabelEn: 'Trips every 30 minutes',
    aboutAr: 'خط باصات منتظم يربط نابلس برام الله والمدن الأخرى.',
    aboutEn: 'A regular bus line connecting Nablus with Ramallah and other cities.',
    photoQuery: 'intercity bus',
    placeholderIcon: Icons.directions_bus_filled,
    placeholderColor: Color(0xFF14B8A6),
  ),
];

// ==================== الصحة ====================
final List<ListingItem> healthData = [
  ListingItem(
    nameAr: 'مستشفى النجاح الوطني الجامعي',
    nameEn: 'An-Najah National University Hospital',
    typeAr: 'مستشفى',
    typeEn: 'Hospital',
    locationAr: 'شارع رفيديا - نابلس',
    locationEn: 'Rafidia St. - Nablus',
    rating: 4.5,
    reviews: 420,
    infoLabelAr: 'طوارئ 24 ساعة',
    infoLabelEn: '24-hour emergency',
    aboutAr: 'مستشفى جامعي كبير يقدم خدمات طبية شاملة وطوارئ على مدار الساعة.',
    aboutEn: 'A large university hospital providing comprehensive medical services and round-the-clock emergency care.',
    photoQuery: 'An-Najah National University Hospital Nablus',
    placeholderIcon: Icons.local_hospital,
    placeholderColor: Color(0xFFE85D5D),
    image: 'assets/images/health/annajah_university_hospital.jpg',
    lat: 32.239066,
    lng: 35.247876,
  ),
  ListingItem(
    nameAr: 'مستشفى رفيديا الحكومي',
    nameEn: 'Rafidia Governmental Hospital',
    typeAr: 'مستشفى حكومي',
    typeEn: 'Governmental Hospital',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 4.2,
    reviews: 310,
    infoLabelAr: 'طوارئ 24 ساعة',
    infoLabelEn: '24-hour emergency',
    aboutAr: 'مستشفى حكومي رئيسي يخدم سكان المدينة والمناطق المحيطة.',
    aboutEn: 'A major governmental hospital serving the city\'s residents and surrounding areas.',
    photoQuery: 'Rafidia Hospital Nablus',
    placeholderIcon: Icons.medical_services,
    placeholderColor: Color(0xFF3B82F6),
    image: 'assets/images/health/rafidia_hospital.jpg',
    lat: 32.225161,
    lng: 35.243655,
  ),
  ListingItem(
    nameAr: 'عيادة النور التخصصية',
    nameEn: 'Al-Noor Specialty Clinic',
    typeAr: 'عيادة تخصصية',
    typeEn: 'Specialty Clinic',
    locationAr: 'شارع فيصل - نابلس',
    locationEn: 'Faisal St. - Nablus',
    rating: 4.6,
    reviews: 130,
    infoLabelAr: 'يعمل 9ص - 6م',
    infoLabelEn: 'Open 9AM - 6PM',
    aboutAr: 'عيادة متخصصة بالكشف والاستشارات الطبية بأحدث الأجهزة.',
    aboutEn: 'A specialty clinic offering medical examinations and consultations with the latest equipment.',
    photoQuery: 'medical clinic interior',
    placeholderIcon: Icons.health_and_safety,
    placeholderColor: Color(0xFF22C55E),
  ),
  ListingItem(
    nameAr: 'مستشفى الاتحاد النسائي',
    nameEn: "Women's Union Hospital",
    typeAr: 'مستشفى نسائي',
    typeEn: "Women's Hospital",
    locationAr: 'شارع الجامعة - نابلس',
    locationEn: 'University St. - Nablus',
    rating: 4.4,
    reviews: 220,
    infoLabelAr: 'طوارئ 24 ساعة',
    infoLabelEn: '24-hour emergency',
    aboutAr: 'مستشفى متخصص برعاية صحة المرأة والولادة، تديره جمعية الاتحاد النسائي العربي في نابلس.',
    aboutEn: "A specialized hospital for women's health and maternity care, run by the Arab Women's Union Society in Nablus.",
    photoQuery: 'Ittihad Womens Union Hospital Nablus',
    placeholderIcon: Icons.pregnant_woman,
    placeholderColor: Color(0xFFEC4899),
    image: 'assets/images/health/ittihad_hospital.jpg',
    lat: 32.228925,
    lng: 35.258989,
  ),
  ListingItem(
    nameAr: 'المستشفى الإنجيلي - سانت لوقا',
    nameEn: "St. Luke's Evangelical Hospital",
    typeAr: 'مستشفى خيري',
    typeEn: 'Charitable Hospital',
    locationAr: 'البلدة القديمة - نابلس',
    locationEn: 'Old City - Nablus',
    rating: 4.5,
    reviews: 260,
    infoLabelAr: 'طوارئ 24 ساعة',
    infoLabelEn: '24-hour emergency',
    aboutAr: 'المستشفى الخيري الوحيد بشمال الضفة الغربية، تأسس عام 1900، ومعروف بأقسام الجراحة العصبية والولادة والعناية المركزة لحديثي الولادة.',
    aboutEn: "The only charitable hospital in the northern West Bank, founded in 1900, well-regarded for its neurosurgery, obstetrics, and neonatal intensive care departments.",
    photoQuery: "St Luke's Evangelical Hospital Nablus",
    placeholderIcon: Icons.local_hospital,
    placeholderColor: Color(0xFF6C5CE7),
    image: 'assets/images/health/stlukes_hospital.jpg',
    lat: 32.222695,
    lng: 35.254909,
  ),
  ListingItem(
    nameAr: 'المستشفى الوطني الحكومي',
    nameEn: 'Al-Watani Governmental Hospital',
    typeAr: 'مستشفى حكومي',
    typeEn: 'Governmental Hospital',
    locationAr: 'نابلس',
    locationEn: 'Nablus',
    rating: 4.1,
    reviews: 300,
    infoLabelAr: 'طوارئ 24 ساعة',
    infoLabelEn: '24-hour emergency',
    aboutAr: 'أقدم مستشفى حكومي فلسطيني، تأسس عام 1888، ويُعد المستشفى الباطني المركزي لمحافظات شمال الضفة الغربية.',
    aboutEn: 'The oldest Palestinian governmental hospital, founded in 1888, serving as the central internal-medicine hospital for the northern West Bank governorates.',
    photoQuery: 'Al Watani Governmental Hospital Nablus',
    placeholderIcon: Icons.local_hospital,
    placeholderColor: Color(0xFFE85D5D),
    image: 'assets/images/health/alwatani_hospital.jpg',
    lat: 32.220980,
    lng: 35.262533,
  ),
  ListingItem(
    nameAr: 'المستشفى العربي التخصصي',
    nameEn: 'Specialized Arab Hospital',
    typeAr: 'مستشفى خاص',
    typeEn: 'Private Hospital',
    locationAr: 'نابلس',
    locationEn: 'Nablus',
    rating: 4.3,
    reviews: 150,
    infoLabelAr: 'طوارئ 24 ساعة',
    infoLabelEn: '24-hour emergency',
    aboutAr: 'مستشفى خاص يقدم خدمات جراحية وطبية متخصصة.',
    aboutEn: 'A private hospital offering specialized surgical and medical services.',
    photoQuery: 'Specialized Arab Hospital Nablus',
    placeholderIcon: Icons.medical_services,
    placeholderColor: Color(0xFF14B8A6),
    image: 'assets/images/health/alarabi_specialty_hospital.jpg',
    lat: 32.224706,
    lng: 35.239961,
  ),
  ListingItem(
    nameAr: 'مستشفى نابلس التخصصي',
    nameEn: 'Nablus Specialty Hospital',
    typeAr: 'مستشفى خاص',
    typeEn: 'Private Hospital',
    locationAr: 'شارع الجامعة - قرب جامعة النجاح - نابلس',
    locationEn: 'University St. - near An-Najah University - Nablus',
    rating: 4.4,
    reviews: 190,
    infoLabelAr: 'طوارئ 24 ساعة',
    infoLabelEn: '24-hour emergency',
    aboutAr: 'مستشفى خاص تأسس عام 2000، متخصص بجراحة القلب المفتوح والقسطرة والقلب التداخلي.',
    aboutEn: 'A private hospital founded in 2000, specializing in open-heart surgery, angiograms, and interventional cardiology.',
    photoQuery: 'Nablus Specialty Hospital cardiac',
    placeholderIcon: Icons.favorite,
    placeholderColor: Color(0xFFEC4899),
    lat: 32.220516,
    lng: 35.246872,
  ),
  ListingItem(
    nameAr: 'عيادة الأسنان الحديثة',
    nameEn: 'Modern Dental Clinic',
    typeAr: 'عيادة أسنان',
    typeEn: 'Dental Clinic',
    locationAr: 'شارع رفيديا - نابلس',
    locationEn: 'Rafidia St. - Nablus',
    rating: 4.5,
    reviews: 175,
    infoLabelAr: 'يعمل 10ص - 8م',
    infoLabelEn: 'Open 10AM - 8PM',
    aboutAr: 'عيادة أسنان متخصصة بأحدث تقنيات التجميل والعلاج.',
    aboutEn: 'A dental clinic specializing in the latest cosmetic and treatment technologies.',
    photoQuery: 'dental clinic',
    placeholderIcon: Icons.medical_information,
    placeholderColor: Color(0xFF3B82F6),
  ),
  ListingItem(
    nameAr: 'مركز نابلس للعلاج الطبيعي',
    nameEn: 'Nablus Physiotherapy Center',
    typeAr: 'علاج طبيعي',
    typeEn: 'Physiotherapy Center',
    locationAr: 'المخفية - نابلس',
    locationEn: 'Al-Makhfiya - Nablus',
    rating: 4.3,
    reviews: 88,
    infoLabelAr: 'يعمل 9ص - 7م',
    infoLabelEn: 'Open 9AM - 7PM',
    aboutAr: 'مركز متخصص بجلسات العلاج الطبيعي وإعادة التأهيل.',
    aboutEn: 'A center specializing in physiotherapy and rehabilitation sessions.',
    photoQuery: 'physiotherapy clinic',
    placeholderIcon: Icons.accessibility_new,
    placeholderColor: Color(0xFF14B8A6),
  ),
  ListingItem(
    nameAr: 'مختبر نابلس المركزي للتحاليل',
    nameEn: 'Nablus Central Medical Lab',
    typeAr: 'مختبر تحاليل',
    typeEn: 'Medical Laboratory',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.2,
    reviews: 140,
    infoLabelAr: 'يعمل 7ص - 9م',
    infoLabelEn: 'Open 7AM - 9PM',
    aboutAr: 'مختبر تحاليل طبية شامل بنتائج سريعة ودقيقة.',
    aboutEn: 'A comprehensive medical lab offering fast and accurate results.',
    photoQuery: 'medical laboratory',
    placeholderIcon: Icons.biotech,
    placeholderColor: Color(0xFF6C5CE7),
  ),
];

// ==================== التعليم ====================
final List<ListingItem> educationData = [
  ListingItem(
    nameAr: 'جامعة النجاح الوطنية',
    nameEn: 'An-Najah National University',
    typeAr: 'جامعة',
    typeEn: 'University',
    locationAr: 'الرابية - نابلس',
    locationEn: 'Al-Rabya - Nablus',
    rating: 4.7,
    reviews: 610,
    infoLabelAr: 'الدوام 8ص - 4م',
    infoLabelEn: 'Hours 8AM - 4PM',
    aboutAr: 'أكبر جامعة فلسطينية، تضم كليات متعددة وحرمًا جامعيًا حديثًا في الرابية.',
    aboutEn: 'The largest Palestinian university, with multiple faculties and a modern campus in Al-Rabya.',
    photoQuery: 'An-Najah National University Nablus campus gate',
    placeholderIcon: Icons.school,
    placeholderColor: Color(0xFF6C5CE7),
    image: 'assets/images/education/annajah_university.jpg',
    lat: 32.2189,
    lng: 35.2400,
  ),
  ListingItem(
    nameAr: 'جامعة النجاح القديمة',
    nameEn: 'An-Najah Old Campus',
    typeAr: 'حرم جامعي',
    typeEn: 'University Campus',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.5,
    reviews: 240,
    infoLabelAr: 'الدوام 8ص - 4م',
    infoLabelEn: 'Hours 8AM - 4PM',
    aboutAr: 'الحرم التاريخي للجامعة بموقع مركزي وسط المدينة.',
    aboutEn: 'The university\'s historic campus, centrally located in the city.',
    photoQuery: 'university building',
    placeholderIcon: Icons.school,
    placeholderColor: Color(0xFF4C6EF5),
  ),
  ListingItem(
    nameAr: 'مدارس نابلس الثانوية',
    nameEn: 'Nablus Secondary Schools',
    typeAr: 'مدرسة',
    typeEn: 'School',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 4.2,
    reviews: 95,
    infoLabelAr: 'الدوام 7:30ص - 1:30م',
    infoLabelEn: 'Hours 7:30AM - 1:30PM',
    aboutAr: 'مجمع مدارس حكومية وخاصة يخدم أحياء المدينة المختلفة.',
    aboutEn: 'A cluster of public and private schools serving the city\'s different neighborhoods.',
    photoQuery: 'school building',
    placeholderIcon: Icons.menu_book,
    placeholderColor: Color(0xFF22C55E),
  ),
  ListingItem(
    nameAr: 'جامعة القدس المفتوحة - فرع نابلس',
    nameEn: 'Al-Quds Open University - Nablus Branch',
    typeAr: 'جامعة',
    typeEn: 'University',
    locationAr: 'شارع فيصل - نابلس',
    locationEn: 'Faisal St. - Nablus',
    rating: 4.3,
    reviews: 180,
    infoLabelAr: 'الدوام 8ص - 5م',
    infoLabelEn: 'Hours 8AM - 5PM',
    aboutAr: 'فرع جامعة تُقدّم برامج تعليم منتظم ومفتوح.',
    aboutEn: 'A university branch offering regular and open-learning programs.',
    photoQuery: 'university building',
    placeholderIcon: Icons.account_balance,
    placeholderColor: Color(0xFF3B82F6),
  ),
  ListingItem(
    nameAr: 'كلية فلسطين التقنية',
    nameEn: 'Palestine Technical College',
    typeAr: 'كلية تقنية',
    typeEn: 'Technical College',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 4.1,
    reviews: 96,
    infoLabelAr: 'الدوام 8ص - 3م',
    infoLabelEn: 'Hours 8AM - 3PM',
    aboutAr: 'كلية متخصصة بالتعليم التقني والمهني.',
    aboutEn: 'A college specializing in technical and vocational education.',
    photoQuery: 'college campus',
    placeholderIcon: Icons.engineering,
    placeholderColor: Color(0xFFF5A623),
  ),
  ListingItem(
    nameAr: 'مركز نابلس لتعليم اللغات',
    nameEn: 'Nablus Language Learning Center',
    typeAr: 'مركز تعليمي',
    typeEn: 'Learning Center',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.4,
    reviews: 67,
    infoLabelAr: 'الدوام 10ص - 8م',
    infoLabelEn: 'Hours 10AM - 8PM',
    aboutAr: 'دورات لغات إنجليزية وأجنبية لمختلف المستويات.',
    aboutEn: 'English and foreign language courses for all levels.',
    photoQuery: 'language classroom',
    placeholderIcon: Icons.translate,
    placeholderColor: Color(0xFF14B8A6),
  ),
  ListingItem(
    nameAr: 'روضة براعم نابلس',
    nameEn: 'Nablus Buds Kindergarten',
    typeAr: 'روضة أطفال',
    typeEn: 'Kindergarten',
    locationAr: 'المخفية - نابلس',
    locationEn: 'Al-Makhfiya - Nablus',
    rating: 4.6,
    reviews: 54,
    infoLabelAr: 'الدوام 7:30ص - 1م',
    infoLabelEn: 'Hours 7:30AM - 1PM',
    aboutAr: 'روضة أطفال بمناهج تعليمية حديثة وأنشطة متنوعة.',
    aboutEn: 'A kindergarten with modern curricula and varied activities.',
    photoQuery: 'kindergarten classroom',
    placeholderIcon: Icons.child_care,
    placeholderColor: Color(0xFFEC4899),
  ),
];

// ==================== البنوك والصرافة ====================
final List<ListingItem> banksData = [
  ListingItem(
    nameAr: 'بنك فلسطين - الفرع الرئيسي',
    nameEn: 'Bank of Palestine - Main Branch',
    typeAr: 'بنك',
    typeEn: 'Bank',
    locationAr: 'شارع الجامعة - نابلس',
    locationEn: 'University St. - Nablus',
    rating: 4.3,
    reviews: 210,
    infoLabelAr: 'يفتح 8:30ص - 3م',
    infoLabelEn: 'Open 8:30AM - 3PM',
    aboutAr: 'الفرع الرئيسي لأكبر بنك فلسطيني، يقدم كافة الخدمات المصرفية وصرافة العملات.',
    aboutEn: 'The main branch of the largest Palestinian bank, offering full banking and currency exchange services.',
    photoQuery: 'bank building',
    placeholderIcon: Icons.account_balance,
    placeholderColor: Color(0xFF14B8A6),
  ),
  ListingItem(
    nameAr: 'البنك العربي',
    nameEn: 'Arab Bank',
    typeAr: 'بنك',
    typeEn: 'Bank',
    locationAr: 'دوار الشهداء - نابلس',
    locationEn: 'Martyrs Circle - Nablus',
    rating: 4.1,
    reviews: 140,
    infoLabelAr: 'يفتح 8:30ص - 3م',
    infoLabelEn: 'Open 8:30AM - 3PM',
    aboutAr: 'فرع بنكي يقدم حسابات جارية وتوفير وخدمات تحويل الأموال.',
    aboutEn: 'A bank branch offering current and savings accounts and money transfer services.',
    photoQuery: 'bank exterior',
    placeholderIcon: Icons.account_balance,
    placeholderColor: Color(0xFF3B82F6),
  ),
  ListingItem(
    nameAr: 'صرافة الاتحاد',
    nameEn: 'Al-Ittihad Exchange',
    typeAr: 'محل صرافة',
    typeEn: 'Currency Exchange',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.4,
    reviews: 88,
    infoLabelAr: 'يفتح 9ص - 7م',
    infoLabelEn: 'Open 9AM - 7PM',
    aboutAr: 'محل صرافة موثوق لتبديل العملات الأجنبية بأسعار يومية محدثة.',
    aboutEn: 'A trusted currency exchange shop with daily updated rates.',
    photoQuery: 'currency exchange shop',
    placeholderIcon: Icons.currency_exchange,
    placeholderColor: Color(0xFFC9A227),
  ),
  ListingItem(
    nameAr: 'بنك القاهرة عمان',
    nameEn: 'Cairo Amman Bank',
    typeAr: 'بنك',
    typeEn: 'Bank',
    locationAr: 'شارع رفيديا - نابلس',
    locationEn: 'Rafidia St. - Nablus',
    rating: 4.2,
    reviews: 165,
    infoLabelAr: 'يفتح 8:30ص - 3م',
    infoLabelEn: 'Open 8:30AM - 3PM',
    aboutAr: 'فرع بنكي يقدم قروض وحسابات توفير وخدمات مصرفية رقمية.',
    aboutEn: 'A bank branch offering loans, savings accounts, and digital banking services.',
    photoQuery: 'bank building',
    placeholderIcon: Icons.account_balance,
    placeholderColor: Color(0xFF6C5CE7),
  ),
  ListingItem(
    nameAr: 'البنك الإسلامي الفلسطيني',
    nameEn: 'Palestine Islamic Bank',
    typeAr: 'بنك',
    typeEn: 'Bank',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.3,
    reviews: 132,
    infoLabelAr: 'يفتح 8:30ص - 3م',
    infoLabelEn: 'Open 8:30AM - 3PM',
    aboutAr: 'بنك يقدم خدمات مصرفية متوافقة مع الشريعة الإسلامية.',
    aboutEn: 'A bank offering Sharia-compliant banking services.',
    photoQuery: 'bank exterior',
    placeholderIcon: Icons.account_balance,
    placeholderColor: Color(0xFF22C55E),
  ),
  ListingItem(
    nameAr: 'صرافة النابلسي',
    nameEn: 'Al-Nabulsi Exchange',
    typeAr: 'محل صرافة',
    typeEn: 'Currency Exchange',
    locationAr: 'شارع فيصل - نابلس',
    locationEn: 'Faisal St. - Nablus',
    rating: 4.1,
    reviews: 59,
    infoLabelAr: 'يفتح 9ص - 8م',
    infoLabelEn: 'Open 9AM - 8PM',
    aboutAr: 'صرافة عائلية بخبرة طويلة وأسعار تنافسية.',
    aboutEn: 'A family-run exchange shop with years of experience and competitive rates.',
    photoQuery: 'currency exchange shop',
    placeholderIcon: Icons.currency_exchange,
    placeholderColor: Color(0xFFC9A227),
  ),
  ListingItem(
    nameAr: 'صندوق التوفير الفلسطيني',
    nameEn: 'Palestinian Savings Fund',
    typeAr: 'بنك',
    typeEn: 'Bank',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 4.0,
    reviews: 47,
    infoLabelAr: 'يفتح 8:30ص - 2:30م',
    infoLabelEn: 'Open 8:30AM - 2:30PM',
    aboutAr: 'خدمات توفير وقروض صغيرة للأفراد وأصحاب المشاريع.',
    aboutEn: 'Savings and micro-loan services for individuals and business owners.',
    photoQuery: 'bank building',
    placeholderIcon: Icons.savings,
    placeholderColor: Color(0xFF3B82F6),
  ),
];

// ==================== الترفيه ====================
final List<ListingItem> entertainmentData = [
  ListingItem(
    nameAr: 'مدينة الملاهي نابلس',
    nameEn: 'Nablus Amusement Park',
    typeAr: 'مدينة ملاهي',
    typeEn: 'Amusement Park',
    locationAr: 'شرق نابلس',
    locationEn: 'East Nablus',
    rating: 4.3,
    reviews: 175,
    infoLabelAr: 'يفتح 3م - 11م',
    infoLabelEn: 'Open 3PM - 11PM',
    aboutAr: 'ألعاب متنوعة للأطفال والعائلات مع مساحات جلوس ومطاعم خفيفة.',
    aboutEn: 'A variety of rides for children and families, with seating areas and light dining.',
    photoQuery: 'amusement park rides',
    placeholderIcon: Icons.attractions,
    placeholderColor: Color(0xFFE85D5D),
  ),
  ListingItem(
    nameAr: 'سينما نابلس',
    nameEn: 'Nablus Cinema',
    typeAr: 'سينما',
    typeEn: 'Cinema',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 4.5,
    reviews: 230,
    infoLabelAr: 'يفتح 12م - 12ص',
    infoLabelEn: 'Open 12PM - 12AM',
    aboutAr: 'صالة عرض سينمائي بتقنية صوت وصورة حديثة وأحدث الأفلام.',
    aboutEn: 'A modern cinema hall with up-to-date sound and picture technology, showing the latest films.',
    photoQuery: 'cinema movie theater',
    placeholderIcon: Icons.local_movies,
    placeholderColor: Color(0xFF6C5CE7),
  ),
  ListingItem(
    nameAr: 'صالة بولينج نابلس',
    nameEn: 'Nablus Bowling Hall',
    typeAr: 'صالة ألعاب',
    typeEn: 'Bowling & Games Hall',
    locationAr: 'شارع الجامعة - نابلس',
    locationEn: 'University St. - Nablus',
    rating: 4.2,
    reviews: 98,
    infoLabelAr: 'يفتح 2م - 12ص',
    infoLabelEn: 'Open 2PM - 12AM',
    aboutAr: 'مسارات بولينج وألعاب فيديو مناسبة للشباب والعائلات.',
    aboutEn: 'Bowling lanes and video games suitable for youth and families.',
    photoQuery: 'bowling alley',
    placeholderIcon: Icons.sports_esports,
    placeholderColor: Color(0xFF22C55E),
  ),
  ListingItem(
    nameAr: 'حديقة نابلس العامة',
    nameEn: 'Nablus Public Garden',
    typeAr: 'حديقة عامة',
    typeEn: 'Public Garden',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 4.4,
    reviews: 142,
    infoLabelAr: 'يفتح 7ص - 10م',
    infoLabelEn: 'Open 7AM - 10PM',
    aboutAr: 'مساحات خضراء ومقاعد جلوس مناسبة للعائلات والأطفال.',
    aboutEn: 'Green spaces and seating areas suitable for families and children.',
    photoQuery: 'public park garden',
    placeholderIcon: Icons.park,
    placeholderColor: Color(0xFF22C55E),
  ),
  ListingItem(
    nameAr: 'مسرح نابلس الثقافي',
    nameEn: 'Nablus Cultural Theater',
    typeAr: 'مسرح',
    typeEn: 'Theater',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.6,
    reviews: 87,
    infoLabelAr: 'حسب جدول العروض',
    infoLabelEn: 'Per show schedule',
    aboutAr: 'مسرح يستضيف عروضًا فنية وثقافية ومسرحية متنوعة.',
    aboutEn: 'A theater hosting a variety of artistic, cultural, and theatrical performances.',
    photoQuery: 'theater stage',
    placeholderIcon: Icons.theater_comedy,
    placeholderColor: Color(0xFF6C5CE7),
  ),
  ListingItem(
    nameAr: 'صالة نادي نابلس الرياضي',
    nameEn: 'Nablus Sports Club Hall',
    typeAr: 'نادي رياضي',
    typeEn: 'Sports Club',
    locationAr: 'الرابية - نابلس',
    locationEn: 'Al-Rabya - Nablus',
    rating: 4.3,
    reviews: 110,
    infoLabelAr: 'يفتح 6ص - 11م',
    infoLabelEn: 'Open 6AM - 11PM',
    aboutAr: 'صالة رياضية ونادي لياقة بدنية بأجهزة حديثة.',
    aboutEn: 'A gym and fitness club with modern equipment.',
    photoQuery: 'gym fitness',
    placeholderIcon: Icons.fitness_center,
    placeholderColor: Color(0xFFF5A623),
  ),
  ListingItem(
    nameAr: 'مقهى الألعاب الإلكترونية',
    nameEn: 'Gaming Lounge Cafe',
    typeAr: 'مقهى ألعاب',
    typeEn: 'Gaming Cafe',
    locationAr: 'شارع فيصل - نابلس',
    locationEn: 'Faisal St. - Nablus',
    rating: 4.1,
    reviews: 76,
    infoLabelAr: 'يفتح 2م - 1ص',
    infoLabelEn: 'Open 2PM - 1AM',
    aboutAr: 'مقهى مخصص لمحبي الألعاب الإلكترونية بأجهزة حديثة.',
    aboutEn: 'A cafe dedicated to gaming enthusiasts with modern consoles and PCs.',
    photoQuery: 'gaming lounge',
    placeholderIcon: Icons.videogame_asset,
    placeholderColor: Color(0xFF14B8A6),
  ),
];

// ==================== خدمات حكومية ====================
final List<ListingItem> governmentData = [
  ListingItem(
    nameAr: 'بلدية نابلس',
    nameEn: 'Nablus Municipality',
    typeAr: 'دائرة حكومية',
    typeEn: 'Government Office',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.0,
    reviews: 160,
    infoLabelAr: 'الدوام 8ص - 3م',
    infoLabelEn: 'Hours 8AM - 3PM',
    aboutAr: 'المقر الرئيسي لبلدية نابلس، يقدم خدمات الترخيص والمعاملات البلدية.',
    aboutEn: 'The main office of Nablus Municipality, providing licensing and municipal services.',
    photoQuery: 'municipality government building',
    placeholderIcon: Icons.account_balance,
    placeholderColor: Color(0xFF3B82F6),
  ),
  ListingItem(
    nameAr: 'دائرة الأحوال المدنية',
    nameEn: 'Civil Affairs Department',
    typeAr: 'دائرة حكومية',
    typeEn: 'Government Office',
    locationAr: 'شارع فيصل - نابلس',
    locationEn: 'Faisal St. - Nablus',
    rating: 3.9,
    reviews: 120,
    infoLabelAr: 'الدوام 8ص - 2:30م',
    infoLabelEn: 'Hours 8AM - 2:30PM',
    aboutAr: 'إصدار وتجديد الهويات ووثائق الأحوال المدنية.',
    aboutEn: 'Issuing and renewing IDs and civil status documents.',
    photoQuery: 'government office',
    placeholderIcon: Icons.badge,
    placeholderColor: Color(0xFF9C6B30),
  ),
  ListingItem(
    nameAr: 'مكتب البريد المركزي',
    nameEn: 'Central Post Office',
    typeAr: 'بريد',
    typeEn: 'Post Office',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.0,
    reviews: 70,
    infoLabelAr: 'الدوام 8ص - 3م',
    infoLabelEn: 'Hours 8AM - 3PM',
    aboutAr: 'خدمات البريد والطرود والتحويلات المالية.',
    aboutEn: 'Postal, parcel, and money transfer services.',
    photoQuery: 'post office',
    placeholderIcon: Icons.local_post_office,
    placeholderColor: Color(0xFFC9A227),
  ),
  ListingItem(
    nameAr: 'محافظة نابلس',
    nameEn: 'Nablus Governorate',
    typeAr: 'دائرة حكومية',
    typeEn: 'Government Office',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.0,
    reviews: 95,
    infoLabelAr: 'الدوام 8ص - 3م',
    infoLabelEn: 'Hours 8AM - 3PM',
    aboutAr: 'المقر الإداري الرئيسي لمحافظة نابلس.',
    aboutEn: 'The main administrative office of the Nablus Governorate.',
    photoQuery: 'government office building',
    placeholderIcon: Icons.apartment,
    placeholderColor: Color(0xFF3B82F6),
  ),
  ListingItem(
    nameAr: 'دائرة ضريبة الدخل',
    nameEn: 'Income Tax Department',
    typeAr: 'دائرة حكومية',
    typeEn: 'Government Office',
    locationAr: 'شارع الجامعة - نابلس',
    locationEn: 'University St. - Nablus',
    rating: 3.8,
    reviews: 54,
    infoLabelAr: 'الدوام 8ص - 2:30م',
    infoLabelEn: 'Hours 8AM - 2:30PM',
    aboutAr: 'خدمات تسجيل ودفع الضرائب للأفراد والشركات.',
    aboutEn: 'Tax registration and payment services for individuals and businesses.',
    photoQuery: 'government office',
    placeholderIcon: Icons.receipt_long,
    placeholderColor: Color(0xFF9C6B30),
  ),
  ListingItem(
    nameAr: 'دائرة تسجيل الأراضي',
    nameEn: 'Land Registry Department',
    typeAr: 'دائرة حكومية',
    typeEn: 'Government Office',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 3.9,
    reviews: 68,
    infoLabelAr: 'الدوام 8ص - 2:30م',
    infoLabelEn: 'Hours 8AM - 2:30PM',
    aboutAr: 'تسجيل وتوثيق ملكية الأراضي والعقارات.',
    aboutEn: 'Registration and documentation of land and property ownership.',
    photoQuery: 'government office',
    placeholderIcon: Icons.map,
    placeholderColor: Color(0xFF14B8A6),
  ),
  ListingItem(
    nameAr: 'مركز شرطة نابلس',
    nameEn: 'Nablus Police Station',
    typeAr: 'مركز شرطة',
    typeEn: 'Police Station',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 4.1,
    reviews: 130,
    infoLabelAr: 'يعمل 24 ساعة',
    infoLabelEn: 'Open 24 hours',
    aboutAr: 'مركز شرطة رئيسي يخدم المدينة على مدار الساعة.',
    aboutEn: 'A main police station serving the city around the clock.',
    photoQuery: 'police station',
    placeholderIcon: Icons.local_police,
    placeholderColor: Color(0xFF3B82F6),
  ),
  ListingItem(
    nameAr: 'الدفاع المدني - نابلس',
    nameEn: 'Nablus Civil Defense',
    typeAr: 'دفاع مدني',
    typeEn: 'Civil Defense',
    locationAr: 'شارع فيصل - نابلس',
    locationEn: 'Faisal St. - Nablus',
    rating: 4.3,
    reviews: 88,
    infoLabelAr: 'يعمل 24 ساعة',
    infoLabelEn: 'Open 24 hours',
    aboutAr: 'خدمات الإطفاء والإنقاذ والطوارئ على مدار الساعة.',
    aboutEn: 'Fire, rescue, and emergency services around the clock.',
    photoQuery: 'fire station',
    placeholderIcon: Icons.local_fire_department,
    placeholderColor: Color(0xFFEF4444),
  ),
];

// ==================== الصيدليات ====================
final List<ListingItem> pharmaciesData = [
  ListingItem(
    nameAr: 'صيدلية النجاح',
    nameEn: 'Al-Najah Pharmacy',
    typeAr: 'صيدلية 24 ساعة',
    typeEn: '24-Hour Pharmacy',
    locationAr: 'شارع الجامعة - نابلس',
    locationEn: 'University St. - Nablus',
    rating: 4.5,
    reviews: 160,
    infoLabelAr: 'تعمل 24 ساعة',
    infoLabelEn: 'Open 24 hours',
    aboutAr: 'صيدلية تعمل على مدار الساعة، توفر جميع الأدوية والمستلزمات الطبية.',
    aboutEn: 'A pharmacy open around the clock, providing all medications and medical supplies.',
    photoQuery: 'pharmacy interior',
    placeholderIcon: Icons.local_pharmacy,
    placeholderColor: Color(0xFF3B82F6),
  ),
  ListingItem(
    nameAr: 'صيدلية الشفاء',
    nameEn: 'Al-Shifa Pharmacy',
    typeAr: 'صيدلية',
    typeEn: 'Pharmacy',
    locationAr: 'وسط البلد - نابلس',
    locationEn: 'Downtown - Nablus',
    rating: 4.3,
    reviews: 110,
    infoLabelAr: 'تعمل 8ص - 11م',
    infoLabelEn: 'Open 8AM - 11PM',
    aboutAr: 'صيدلية بموقع مركزي تقدم استشارات دوائية مجانية.',
    aboutEn: 'A centrally located pharmacy offering free medication consultations.',
    photoQuery: 'pharmacy shelves medicine',
    placeholderIcon: Icons.local_pharmacy,
    placeholderColor: Color(0xFF22C55E),
  ),
  ListingItem(
    nameAr: 'صيدلية الرحمة',
    nameEn: 'Al-Rahma Pharmacy',
    typeAr: 'صيدلية 24 ساعة',
    typeEn: '24-Hour Pharmacy',
    locationAr: 'رفيديا - نابلس',
    locationEn: 'Rafidia - Nablus',
    rating: 4.4,
    reviews: 140,
    infoLabelAr: 'تعمل 24 ساعة',
    infoLabelEn: 'Open 24 hours',
    aboutAr: 'صيدلية تعمل على مدار الساعة مع خدمة توصيل للمنازل.',
    aboutEn: 'A 24-hour pharmacy offering home delivery service.',
    photoQuery: 'pharmacy store',
    placeholderIcon: Icons.local_pharmacy,
    placeholderColor: Color(0xFFE85D5D),
  ),
  ListingItem(
    nameAr: 'صيدلية الأمل',
    nameEn: 'Al-Amal Pharmacy',
    typeAr: 'صيدلية',
    typeEn: 'Pharmacy',
    locationAr: 'شارع فيصل - نابلس',
    locationEn: 'Faisal St. - Nablus',
    rating: 4.2,
    reviews: 85,
    infoLabelAr: 'تعمل 8ص - 10م',
    infoLabelEn: 'Open 8AM - 10PM',
    aboutAr: 'صيدلية عائلية تقدم خدمة شخصية ومتابعة دقيقة للزبائن.',
    aboutEn: 'A family pharmacy offering personalized service and careful follow-up for customers.',
    photoQuery: 'pharmacy counter',
    placeholderIcon: Icons.local_pharmacy,
    placeholderColor: Color(0xFFC9A227),
  ),
];